export const ALL_STATUS_ID = {
  OPEN: 1,
  WAIT_LIST: 2,
  CLOSED: 3,
  NOT_LISTED: 4,
  IN_PROGRESS: 5,
  WAITING_APPROVE: 6,
  PENDING_REVIEW: 7,
  APPROVED: 8
}

export const AUTHOR_STATUS_TRANSITIONS = {
  [ALL_STATUS_ID.OPEN]: [ALL_STATUS_ID.IN_PROGRESS, ALL_STATUS_ID.WAIT_LIST],
  [ALL_STATUS_ID.WAIT_LIST]: [ALL_STATUS_ID.OPEN, ALL_STATUS_ID.IN_PROGRESS],
  [ALL_STATUS_ID.IN_PROGRESS]: [ALL_STATUS_ID.OPEN, ALL_STATUS_ID.WAITING_APPROVE],
  [ALL_STATUS_ID.PENDING_REVIEW]: [ALL_STATUS_ID.IN_PROGRESS],
}

export const BUYER_STATUS_TRANSITIONS = {
  [ALL_STATUS_ID.WAITING_APPROVE]: [ALL_STATUS_ID.APPROVED, ALL_STATUS_ID.PENDING_REVIEW],
}